### ISSUE TITLE
Support patterns for Gitlab.com

### ISSUE THREAD

**Issue by Chris2011** [markiewb/nb-git-open-in-external-repoviewer#20]
In my daily work, I have to use gitlab, but when I want to use your tool, to open the external url, it doesn't work, because I don't get an entry. I think that the support for gitlab is missing.

Regards

Chris

**Comment by markiewb** [comment]
Hi Chris. It is not supported yet. Do you like to provide a PR?
It is easy. You only have to provide one class and a test .

See 
* https://github.com/markiewb/nb-git-open-in-external-repoviewer/blob/master/src/main/java/de/markiewb/netbeans/plugin/git/openinexternalviewer/strategies/GitBlitStrategyImpl.java
* https://github.com/markiewb/nb-git-open-in-external-repoviewer/blob/master/src/test/java/de/markiewb/netbeans/plugin/git/openinexternalviewer/strategies/GitBlitStrategyTest.java

**Comment by markiewb** [comment]
@Chris2011 : Do you know a public gitlab server where I can try it out?

**Comment by Chris2011** [comment]
unfortunately no but maybe you will find at google with this phrase a free one: site:git.*.* gitlab.

**Comment by markiewb** [comment]
https://gitlab.com/paulodiovani/ci-tests-nodejs looks promising.
@Chris2011: Do you use a private gitlab installation at your workplace or are patterns for gitlab.com enough?

**Comment by Chris2011** [comment]
In our company we have this url: https://git.company.net/ so we have a private gitlab repo in our company.

**Comment by markiewb** [comment]
@Chris2011: The pattern of your gitlab installation is too generic. I do not know, what is the distinguish part there. But I extracted the patterns into a "property file", which can be altered by you for your needs. 

In the options panel (#27 )
* duplicate the lines of ```gitlab``` (starting with ```gitblit.```)
* replace the ```gitblit``` identifier with a new identifier like ```gitlabAtWork```
* update the patterns to match your server url
* add your new new identifier to ```$.global.strategies```

**Comment by Chris2011** [comment]
Thx, I will test your plugin soon :) :+1:

**Comment by Chris2011** [comment]
Added new pattern to gitlab, works as expected, thx :) :+1:
