### ISSUE TITLE
pull request action on bitbucket label error

### ISSUE THREAD

**Issue by mkleint** [markiewb/nb-git-open-in-external-repoviewer#25]
testing the prerelease containing the pull request action, there's something wrong with the label, pls see screenshot

https://github.com/markiewb/nb-git-open-in-external-repoviewer/blob/master/src/main/java/de/markiewb/netbeans/plugin/git/openinexternalviewer/PullRequestAction.java#L19

<img width="510" alt="2015-09-06_1247" src="https://cloud.githubusercontent.com/assets/178549/9702183/f02c950e-5495-11e5-97d2-2995e7a66214.png">

**Comment by markiewb** [comment]
Thank you Milos. Should be fixed. https://github.com/markiewb/nb-git-open-in-external-repoviewer/releases/tag/v1.3.8.1-SN
