### ISSUE TITLE
Configuration-Migrator from 1.4.0.2 to 1.4.1.0 does not work - Options.resetToDefault() is wrong

### ISSUE THREAD

**Issue by mkleint** [markiewb/nb-git-open-in-external-repoviewer#34]
effectively any updates coming from the plugin will not be propagated to the user as the properties are dumped into user settings area on first installation. The user has to click 'reset to default' in Tools/Options to get the latest uptodate values after upgrade.

**Comment by markiewb** [comment]
Mhh. So the MD5-code is wrong.

See my try at
https://github.com/markiewb/nb-git-open-in-external-repoviewer/commit/2fd1d3b045a6695a7153a7e8ae71661c9a258a0d#diff-61cc546ff83c718ae088e19acd7b0706R31

With kind regards, markiewb

2015-11-19 12:02 GMT+01:00 Milos Kleint <notifications@github.com>:

**Comment by markiewb** [comment]
@mkleint : Please try https://github.com/markiewb/nb-git-open-in-external-repoviewer/releases/download/v1.4.1.1/open.url.of.git.repository.hoster-1.4.1.1.nbm and give me feedback. After that I will provide an update to the plugin center. At least it worked once at my machine *g*
