### ISSUE TITLE
Possibility to add keyboard shortcuts (preferably bindable within the Netbeans settings)

### ISSUE THREAD

**Issue by bravoman** [markiewb/nb-git-open-in-external-repoviewer#35]
Great addon!

It would be even more awesome to have a keyboard shortcut for each of the actions that your (possibly provide) for the currently selected item. So here's my feature request for that ;)

**Comment by markiewb** [comment]
Fixed in 1.4.2.1
![2016-03-10_19h40_58](https://cloud.githubusercontent.com/assets/1857095/13681363/2467ca06-e6fd-11e5-8b8c-5316e622e2ac.png)

**Comment by markiewb** [comment]
@bravoman: Done. If you like this plugin, please donate and spread the news by blogging about it.
