### ISSUE TITLE
Use configured browser to open links

### ISSUE THREAD

**Issue by bravoman** [markiewb/nb-git-open-in-external-repoviewer#36]
The links opened by this extension / addon seem to open in IE by default when working on a Windows environment. Though I can understand that will work in most cases. This is definitely not the preferred browser of most of Netbeans users (even the ones that use windows ;)). 

It would be awesome if it could load the systems default browser instead. 

Like I have set here:
![default browser](https://cloud.githubusercontent.com/assets/1729802/13670428/315789f0-e6ca-11e5-9b0c-092274f6fc5e.png)

**Comment by markiewb** [comment]
fixed in 1.4.2
