### ISSUE TITLE
Add to editor context menu 

### ISSUE THREAD

**Issue by Chris2011** [markiewb/nb-git-open-in-external-repoviewer#37]
I know there is a plugin called github navigator: https://github.com/jglick/nbgittricks but because of your plugin can handle gitlab, bitbucket, github and what I added to it, it would be very nice, if we can have a context menu für each file to open this file in the git repo and inside a file, a context menu entry and shortcut to open the file with a specific line is selected. If I have time, I could do a pull request, but atm it is only a feature request to you.

Regards

Chris

**Comment by markiewb** [comment]
![image](https://cloud.githubusercontent.com/assets/1857095/19821329/0852fc92-9d5e-11e6-9f82-c800203dfe50.png)

This feature already exists. Right click on the file tab and you will see the menu entry f.e. for github.
Ok, we could make this more obvious by adding it to the context menu of the editor. http://wiki.netbeans.org/DevFaqActionAddToContextMenuOfAllEditors
